# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjk1j2_riCoAYzO24OJZKUzpxljO1Hqs
"""

import time

def calculate(x):
    return x**2 - x**2 + 4*x - 5*x + x + x

x = 3.0

while True:
    user_input = input("Enter iterations count (or 'q' to quit): ").strip()

    # 1. Проверка на выход
    if user_input.lower() == 'q':
        print("Exiting program...")
        break

    # 2. Проверка на число
    try:
        n = int(user_input)
    except ValueError:
        print("Error: Input must be an integer!\n")
        continue

    # 3. Проверка диапазона
    if n <= 0:
        print("Error: Number must be greater than zero!\n")
        continue

    # 4. Вычисления
    start = time.perf_counter()
    result = calculate(x)  # Однократное вычисление результата
    for _ in range(n): pass  # Пустой цикл для замера времени
    end = time.perf_counter()

    # 5. Вывод результатов
    print(f"Result: {result}")
    print(f"Time: {end - start:.6f} seconds\n")